webdriver:
  timeouts:
    explicit_wait: 10
    page_load: 10

  browser:
    window_size: 1920,1080

base_urls:
  bspb: https://idemo.bspb.ru/
  the_internet: https://the-internet.herokuapp.com/

faker:
  locale: ru_RU
